# Generated by Django 4.2.3 on 2023-07-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=80)),
                ('img', models.ImageField(upload_to='')),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Societe',
            },
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=80)),
                ('prenom', models.CharField(blank=True, max_length=80)),
                ('tel', models.CharField(blank=True, max_length=80)),
                ('num_trans', models.CharField(blank=True, max_length=80)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('societe', models.ManyToManyField(to='angaapp.societe')),
            ],
            options={
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
