# Generated by Django 4.2.3 on 2023-07-31 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
            },
        ),
        migrations.CreateModel(
            name='Heure_d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=80)),
                ('img', models.ImageField(upload_to='')),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Societe',
            },
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=80)),
                ('prenom', models.CharField(blank=True, max_length=80)),
                ('date', models.DateField()),
                ('tel', models.CharField(blank=True, max_length=80)),
                ('num_trans', models.CharField(blank=True, max_length=80)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='angaapp.destination')),
                ('societe', models.ManyToManyField(to='angaapp.societe')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='angaapp.heure_d')),
            ],
            options={
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
