# Generated by Django 4.2.3 on 2023-07-29 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('angaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heure_d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='reservations',
            name='time',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='angaapp.heure_d'),
            preserve_default=False,
        ),
    ]
