# Generated by Django 4.2.3 on 2023-08-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angaapp', '0002_alter_reservations_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='code_reservation',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
